name: Build Loongarch64 Packages

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-base-packages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true

      - name: Restore and save Nix store
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size-linux: 3G
          purge: true
          purge-prefixes: nix-${{ runner.os }}-
          purge-created: 0
          purge-last-accessed: 0
          purge-primary-key: never

      - name: Configure Cachix
        uses: cachix/cachix-action@v14
        with:
          name: loongarch64-cross-test
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build system packages for Loongarch64
        run: |
          ./build.sh environment.systemPackages

      - name: Build python packages for Loongarch64
        run: |
          ./build.sh pkgSet.pythonPackages

      - name: Build base cli packages for Loongarch64
        run: |
          ./build.sh pkgSet.baseCliPackages

      - name: Build other packages for Loongarch64
        run: |
          ./build.sh pkgSet.otherPackages
