name: Build Loongarch64 Packages

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
        with:
          extra-conf: |
            experimental-features = nix-command flakes
            system-features = recursive-nix

      - name: Configure Cachix
        uses: cachix/cachix-action@v14
        with:
          name: loongarch64-cross-test
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build packages for Loongarch64
        run: |
          ./build.sh
