name: Update Flake Lock
on:
  schedule:
    - cron: '0 18 * * *' # UTC 00:00
  workflow_dispatch:

permissions:
  contents: write # 授予提交权限

jobs:
  update-flake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
        with:
          extra-conf: |
            experimental-features = nix-command flakes
            system-features = recursive-nix

      - name: Update flake.lock
        run: nix flake update

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
            commit_message: auto update flake.lock
